FROM node:20-alpine AS builder
WORKDIR /src

ARG BACKEND_URL=http://localhost:8000
ENV BACKEND_URL=${BACKEND_URL}

COPY frontend/package*.json ./
RUN npm ci --legacy-peer-deps
COPY frontend/ .
RUN npm run build

FROM node:20-alpine
WORKDIR /app

COPY --from=builder /src ./

EXPOSE 3000
CMD ["npm", "start"]

