"""sync schema with models

Revision ID: dcce824fc07a
Revises: cefcab0ca8e1
Create Date: 2026-08-13 08:26:43.683801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'dcce824fc07a'
down_revision = 'cefcab0ca8e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('risk_rating', sa.String(length=20), nullable=True),
    sa.Column('compliance_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_assets_user_id'), ['user_id'], unique=False)

    op.create_table('audit_trails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_trails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_trails_user_id'), ['user_id'], unique=False)

    op.create_table('deepfake_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('media_url', sa.String(length=1024), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('analysis_details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deepfake_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deepfake_events_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('product_info', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('runtime_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=False),
    sa.Column('enforcement_mode', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runtime_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runtime_policies_user_id'), ['user_id'], unique=False)

    op.create_table('threat_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('threat_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('impact_level', sa.String(length=20), nullable=True),
    sa.Column('mitigation_strategy', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_predictions_user_id'), ['user_id'], unique=False)

    op.create_table('vendors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('service_provided', sa.String(length=255), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_user_id'), ['user_id'], unique=False)

    op.create_table('dark_web_mentions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('source_forum', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('threat_actor', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['ai_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dark_web_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dark_web_mentions_user_id'), ['user_id'], unique=False)

    # NOTE: autogenerate was run against SQLite, which does not reflect foreign
    # keys or named constraints. That produced spurious alter_column(created_at)
    # nullability changes and FK drop/create pairs on the pre-existing alerts,
    # projects, reports and scans tables. Those constraints already exist and
    # are correct on PostgreSQL, and `drop_constraint(None, ...)` is not even
    # executable there. They have been removed deliberately — this migration is
    # purely additive: new tables, the two missing scans columns, new indexes.
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trust_score', sa.Integer(), nullable=True))
        # JSONB on PostgreSQL (matches the model), plain JSON elsewhere so the
        # same migration still runs against SQLite in local/dev.
        batch_op.add_column(sa.Column(
            'compliance_frameworks',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
            nullable=True,
        ))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_oauth_provider'), ['oauth_provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_oauth_provider_id'), ['oauth_provider_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_oauth_provider_id'))
        batch_op.drop_index(batch_op.f('ix_users_oauth_provider'))

    # Mirrors the pruning in upgrade(): only the additive changes are reversed.
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('compliance_frameworks')
        batch_op.drop_column('trust_score')

    with op.batch_alter_table('dark_web_mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dark_web_mentions_user_id'))

    op.drop_table('dark_web_mentions')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_user_id'))

    op.drop_table('vendors')
    with op.batch_alter_table('threat_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_predictions_user_id'))

    op.drop_table('threat_predictions')
    with op.batch_alter_table('runtime_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runtime_policies_user_id'))

    op.drop_table('runtime_policies')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_transaction_id'))

    op.drop_table('payments')
    with op.batch_alter_table('deepfake_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deepfake_events_user_id'))

    op.drop_table('deepfake_events')
    with op.batch_alter_table('audit_trails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_trails_user_id'))

    op.drop_table('audit_trails')
    with op.batch_alter_table('ai_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_assets_user_id'))

    op.drop_table('ai_assets')
    # ### end Alembic commands ###
